### ISSUE TITLE
Remove app from store

### ISSUE THREAD

**Issue by double-u-a** [chikichikitube/android#3]
Given the move to softsubs for new videos and a lack of android exoplayer support for styled .ass files the app will only be able to show some hardsubs and many videos without subs at all. I have had messages from people confused why subs aren't showing and I can't really do anything about it on my side.

The alternative is to support the simpler webvtt subs format as I have made those available for all the softsubbed videos.

This would take time though, I suggest we take the app off the Play Store/F-Droid for now as until it has webvtt support.

**Comment by AbdullahSako** [comment]
Due to the lack of time i wont be able to work on the app further to support the subs.
I will respect your wishes and remove the app from the store and fdroid in the coming days.

**Comment by double-u-a** [comment]
Thanks, and thanks again for the app, it was very well recieved and hopefully you got the learning out of it that you wanted :)
